### ISSUE TITLE
Does not work in Version 4.0.2

### ISSUE THREAD

**Issue by ParaArchi** [chenpaner/Rhino-to-blender#2]
Python: Traceback (most recent call last):
  File "C:\Users\myw\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Rhino-to-blender-main\__init__.py", line 339, in execute
    bpy.ops.export_scene.obj(filepath=os.path.join(os.path.dirname(__file__), 'assets', 'Blender to Rhino-mesh.obj'), use_selection=True,axis_forward='Y',axis_up='Z')
  File "D:\blender-4.0.1-windows-x64\blender-4.0.1-windows-x64\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
AttributeError: Calling operator "bpy.ops.export_scene.obj" error, could not be found

**Comment by FF-Studio** [comment]
Same problem, but I have "line 64" instead of line "339"

**Comment by chenpaner** [comment]
Fixed!! [https://github.com/chenpaner/Rhino-to-blender/releases/tag/1.1.1](url)
